spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketflow
    username: ticketflow_app
    password: ticketflow_mdp
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ticketflow
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    default-schema: ticketflow
    baseline-on-migrate: true
    schemas:
      - ticketflow